# Generated by Django 3.1.3 on 2020-11-29 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0002_auto_20201129_0443"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="room",
            options={"ordering": ("-building",)},
        ),
    ]
