# Generated by Django 3.1.3 on 2020-11-26 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0002_auto_20201126_0843"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="attendees_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
