# Generated by Django 3.1.3 on 2020-12-14 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0005_auto_20201210_1841"),
        ("reservations", "0005_auto_20201214_1617"),
    ]

    operations = []
